<?php
if (!defined('_GNUBOARD_')) exit; // 개별 페이지 접근 불가

$_errArray = array(
	array("0","존재하지 않는 반품건입니다","This return does not exist-Error(0)"),
	array("1","반품상태 오류입니다.","Return condition error-Error(1)"),
	array("2","해당매장 반품건이 아닙니다","Not a refund of our store-Error(2)"),
	array("3","반품코드 오류입니다.","Return code error-Error(3)"),
	array("4","거부된 반품건이 아닙니다","Not a rejected return-Error(4)"),
	array("5","이미 손망실처리된 반품건입니다","Already a return that has been handled for loss and damage-Error(5)"),
	array("6","키값 오류입니다","Key value error-Error(6)"),
	array("7","재고 히스토리 최종건이 아닙니다","Not final case of stock history-Error(7)"),
	array("8","반품출고된 재고가 아닙니다","Not a stock that has been returned-Error(8)"),
	array("9","손망실처리를 할 수 없는 상태입니다","Cannot be handled for loss and damage-Error(9)"),
	array("10","구분값 오류입니다","Classification value error-Error(10)"),
	array("11","처리할 제품을 선택하십시오","Select product for processing-Error(11)"),
	array("12","매장키값이 유효하지 않습니다","Store key value is not valid-Error(12)"),
	array("13","매장이 존재하지 않습니다","Store does not exist-Error(13)"),
	array("14","장바구니에 담을 상품이 없습니다","There is no product to place in Shopping Cart-Error(14)"),
	array("15","존재하지 않는 상품 또는 발송수량오류 입니다","Product does not exist or Delivery quantity error-Error(15)"),
	array("16","존재하지 않는 발주건입니다","Order does not exist-Error(16)"),
	array("17","접근권한이 없습니다","Not authorized to access-Error(17)"),
	array("18","발주취소가 불가합니다","Cannot cancel order-Error(18)"),
	array("19","발주상태 오류입니다","Order status error-Error(19)"),
	array("20","바코드번호 오류입니다","Barcode number error-Error(20)"),
	array("21","바코드체크 오류입니다","Barcode check error-Error(21)"),
	array("22","해당 발주건에 주문되지 않은 상품입니다","Product has not been ordered in this order.-Error(22)"),
	array("23","해당 발송건에 없는 상품입니다","Product does not exist in the order form.-Error(23)"),
	array("24","이미 입고처리된 바코드번호 입니다","Already stocked in-Error(24)"),
	array("25","존재하지 않는 제품입니다","Product does not exist-Error(25)"),
	array("26","존재하지 않는 발주건 또는 발주수량 오류입니다","Order does not exist and/or Order quantity error-Error(26)"),
	array("27","매장에 존재하지 않는 제품입니다","Product does not exist in the store-Error(27)"),
	array("28","매장 재고에 없는 상품입니다","Product is not in the store inventory-Error(28)"),
	array("29","출고 또는 출고준비중 상품입니다","Product has been released or preparing for release-Error(29)"),
	array("30","반품대기중인 상품이 아닙니다","product is not in refund waiting status-Error(30)"),
	array("31","반품등록할 상품이 없습니다","No product has been registered for return-Error(31)"),
	array("32","결제취소수단을 선택하십시오","Select method to cancel payment-Error(32)"),
	array("33","반품금액이 올바르지 않습니다","Return price is not correct-Error(33)"),
	array("34","바코드번호 오류상품이 있습니다","There is a product with barcode number error-Error(34)"),
	array("35","반품가능한 상품이 아닙니다.(매장제품이 아니거나 이미 매장재고에 있음.)","Product cannot be returned (Not a product in the store or is already in the store)-Error(35)"),
	array("36","반품가능한 상품이 아닙니다.(판매되지 않았거나 이미 반품됨.)","Product cannot be returned (Product has not been sold or has been returned)-Error(36)"),
	array("37","상품명이 입력되지 않은 항목이 있습니다","Item is missing product name-Error(37)"),
	array("38","구매금액이 올바르지 않습니다","Incorrect purchase price-Error(38)"),
	array("39","반품금액이 올바르지 않습니다.","Incorrect return price-Error(39)"),
	array("40","총반품금액 오류입니다","Total return price error-Error(40)"),
	array("41","총결제금액보다 총반품금액이 많습니다","Total return price is greater than total payment price-Error(41)"),
	array("42","카드+현금 결제취소시 현금금액을 정확히 입력하십시오","Accurately enter the cash price when cancelling card + cash-Error(42)"),
	array("43","주문외 입고할 상품이 없습니다","No products for income other than order-Error(43)"),
	array("44","주문외 입고건 코드 오류입니다","Income code error other than order-Error(44)"),
	array("45","주문외 입고건 바코드번호가 아닙니다","Not an income barcode number other than order-Error(45)"),
	array("46","처리할 미인수건이 없습니다","No not received case to process-Error(46)"),
	array("47","존재하지 않는 제품이 있습니다","There is a product that does not exist-Error(47)"),
	array("48","출고되지 않은 제품이 있습니다","There is a product that has not been released-Error(48)"),
	array("49","이미 정상입고처리된 제품이 있습니다","There is a product that has already been properly processed for income-Error(49)"),
	array("50","비밀번호가 넘어오지 않았습니다.","Password has not been turned over-Error(50)"),
	array("51","비밀번호가 일치하지 않습니다","Password does not match-Error(51)"),
	array("52","직원명을 입력하세요","Enter employee name-Error(52)"),
	array("53","존재하지 않는 회원자료입니다","Member data does not exist-Error(53)"),
	array("54","판매등록할 상품이 없습니다","There is no product to register for sales-Error(54)"),
	array("55","결제수단을 선택하십시오","Select payment method-Error(55)"),
	array("56","바코드번호 오류상품이 있습니다","There is a product with barcode number error-Error(56)"),
	array("57","매장재고에 존재하지 않는 상품이  있습니다","There is a product that does not exist in the store inventory-Error(57)"),
	array("58","매장상품이 아닙니다","Not a store product-Error(58)"),
	array("59","불량재고상품이 있습니다","There is a defect product -Error(59)"),
	array("60","반품출고중인 상품이 있습니다","There is a product that is being returned-Error(60)"),
	array("61","제품가격,판매가,할인가,소계금액이 음수인 항목이 있습니다","There is an item of negative quantity among product price, sales price, discount price, and subtotal amount-Error(61)"),
	array("62","할인금액이 판매가보다 큰 항목이 있습니다","An item has higher discount price than sales price-Error(62)"),
	array("63","소계금액오류(음수가격 등)인 항목이 있습니다","There is an item with subtotal amount error (negative price and etc.)-Error(63)"),
	array("64","상품명이 입력되지 않은 항목이 있습니다","There is an item with no product name-Error(64)"),
	array("65","수동판매건에 판매가,할인가,소계금액이 음수인 항목이 있습니다","There is an item of negative quantity among sales price, discount price, and subtotal amount in manual sales -Error(65)"),
	array("66","수동판매건에 할인금액이 판매가보다 큰 항목이 있습니다","An item has higher discount price than sales price in the manual sales-Error(66)"),
	array("67","수동판매건에 소계금액오류(음수가격 등)인 항목이 있습니다","There is an item with subtotal amount error (negative price and etc.)-Error(67)"),
	array("68","금액합계 오류입니다","Total amount error-Error(68)"),
	array("69","할인합계 오류입니다","Discount total amount error-Error(69)"),
	array("70","총결제금액 오류입니다","Total payment price error-Error(70)"),
	array("71","카드+현금 결제시 현금금액을 정확히 입력하십시오","Accurately enter the cash price when paying with card + cash-Error(71)"),
	array("72","매장에서 판매된 제품이 아닙니다","Product has not been sold in the store-Error(72)"),
	array("73","이미 반품된 제품입니다","Product has already been returned-Error(73)"),
	array("74","판매된 제품이 아닙니다","Not a product that has been sold-Error(74)"),
	array("75","출고(준비중) 또는 불량재고 상품입니다","Product has been released (or being prepared) and/or is in defect inventory-Error(75)"),
	array("76","가격적용할 상품을 선택하십시오","Select the product to apply price-Error(76)"),
	array("77","매장가를 양수로 입력하십시오","Enter the store price as positive number-Error(77)"),
	array("78","매장에 존재하지 않는 재고 또는 출고준비중인 재고입니다","Stock does not exist in store or is being prepared for release-Error(78)"),
	//array("79","접근권한이 없습니다. 업체회원이시라면 업체아이디로 로그인하십시오","No authorization to access. Please log in (Company ID if Company Member)-Error(79)"),

	array("79","'회원아이디가 없습니다","Member ID is missing"),
	array("80","매장코드값이 없습니다","Store code is missing"),
	array("81","매장코드는 영문자, 숫자, _ 만 입력하세요","Only english or number is available to store code"),
	array("82","매장코드는 최소 6글자 이상 입력하세요","Store code must be at least 6 characters"),
	array("83","이미 등록된 매장코드 입니다","Store code already exists"),
	array("84","매장명이 없습니다","Store name is missing"),
	array("85","비밀번호가 넘어오지 않았습니다","Password is missing"),
	array("86","비밀번호가 일치하지 않습니다","Password does not match"),
	array("87","반품처리할 상품이 없습니다","There is no product to return"),
	array("88","이미 본사재고에 입고된 제품 또는 해당매장에 출고되지 않은 제품입니다","Already Stocked in or never sold to the store"),
	array("89","매장 ID가 존재하지 않습니다","Store ID does not exist"),
	array("90","적요를 입력하세요","The brief is missing"),
	array("91","본사재고에 없는 바코드번호 입니다","No stock is exist in the center with this barcode "),
	array("92","불량재고입니다","Defected stock"),
	array("93","출고준비중인 제품입니다","In ready to stock out"),
	array("94","배송수량 초과입니다","Order count over"),
	array("95","출력할 내역이 없습니다","No list to save excel"),
	array("96","카테고리가 없습니다","Category does not exist"),
	array("97","서브카테고리가 있어 삭제할 수 없습니다","Can not be deleted because Sub category exist."),
	array("98","해당 카테고리로 등록된 상품이 있어 삭제할 수 없습니다","Can not be deleted because products with this category exist."),
	array("99","발급되지 않았거나 이미 입고처리된 바코드번호 입니다","Not issued or already stocked in"),
	array("100","반품 가능한 상품이 아닙니다","Product cannot be returned"),
	array("101","해당 발주건에서 발급한 바코드번호가 아닙니다","Not issued from this order"),
	array("102","발송할 상품이 없습니다","No products to send"),
	array("103","발송수량오류 또는 발송단가오류 입니다","Delivery quantity error or Sales price error"),
	array("104","바코드 발행갯수를 10,000 미만의 양수로 입력하세요.","Enter issue number under 10000"),
	array("105","발급수량 오류입니다","Issue number error"),
	array("106","상품을 선택하십시오","Select products to issue barcode"),
	array("107","바코드번호 또는 발급수량 오류상품이 있습니다","There is a product with barcode number error or issue number error-Error(34)"),
	array("108","인수건 일괄발급을 진행할 수 없습니다","Cannot proceed any more."),
	array("109","해당발주건 바코드가 이미 발행되었습니다","Barcodes of this order is already issued"),
	array("110","미인수건 처리건수 오류입니다","Not received number error"),
	array("111","삭제할 수 없는 상품입니다","Can not be deleted."),
	array("112","원본제품 그룹키값이 비정상입니다.","The group key value of source product is not valid"),
	array("113","파일 또는 글내용의 크기가 서버에서 설정한 값을 넘어 오류가 발생하였습니다","File upload error"),
	array("114","등록할 상품이 없습니다","There is no product to register-Error(54)"),
	array("115","바코드에 중복된 값이 있습니다","Barcode duplication error"),
	array("116","바코드번호는 영문자, 숫자만 입력가능합니다","Only english or number is available to barcode"),
	array("117","동일 바코드로 이미 등록된 상품이 있습니다","There is already registered product with the barcode"),
	array("118","색상/디자인이 입력되지 않았습니다","Color(design) of product is missing"),
	array("119","제품명을 입력하세요","Name of product is missing"),
	array("120","카테고리키값이 비정상입니다","Category value is not valid"),
	array("121","적용기기키값이 비정상입니다","Device value is not valid"),
	array("122","가격설정값 오류입니다","Error in prices of the product"),
	array("123","작성세션오류입니다","Write session error"),
	array("124","그룹키값이 유효하지 않습니다","The group key of the product is not valid"),
	array("125","가격을 양수로 입력하십시오","Price value must be positive"),
	array("126","존재하지 않는 재고 또는 출고준비중인 재고입니다","Stock does not exist in center or is being prepared for release-Error(78)"),
	array("127","등록시에는 키값을 사용하지 않습니다","Key value is not needed"),

	array("128","예치금이 부족합니다.","Not enough deposit to order"),
	array("129","입고취소를 할 수 없습니다.","Stock-in cannot be cancelled"),
	array("130","인수완료되지 않은 재고입니다.","Stock-in confirm required"),
	array("131","인수완료되지 않은 재고가 있습니다.\n주문건 인수완료후 처리할 수 있습니다.","Stock-in confirm required before processing"),
	array("132","이름을 입력하세요","Enter name-Error(132)"),
	array("133","적립금 사용가능액이 유효하지 않습니다","Invalid M.ship value error."),
	array("134","멤버쉽 사용금액 초과입니다","M.ship is not enough for pay"),
	array("135","멤버쉽금액이 총결제금액보다 많습니다","Can not apply M.ship over the total_pay amount"),
	array("136","한글","English"),
	array("137","한글","English"),
	array("138","한글","English"),
	array("139","한글","English"),
	array("140","한글","English"),
	array("141","한글","English"),
	array("142","한글","English"),
	array("143","한글","English"),
	array("144","한글","English"),
	array("145","한글","English"),
	array("146","한글","English"),
	array("147","한글","English"),
	array("148","한글","English"),
	array("149","한글","English"),
	array("150","한글","English"),
	array("151","한글","English"),
	array("152","한글","English"),
	array("153","한글","English"),
	array("154","한글","English"),
	array("155","한글","English"),
	array("156","한글","English"),
	array("157","한글","English"),
	array("158","한글","English"),
	array("159","한글","English"),
	array("160","한글","English"),
	array("161","한글","English"),
	array("162","한글","English"),
	array("163","한글","English"),
	array("164","한글","English"),
	array("165","한글","English"),
	array("166","한글","English"),
	array("167","한글","English"),
	array("168","한글","English"),
	array("169","한글","English"),
	array("170","한글","English"),
	array("171","한글","English"),
	array("172","한글","English"),
	array("173","한글","English"),
	array("174","한글","English"),
	array("175","한글","English"),
	array("176","한글","English"),
	array("177","한글","English"),
	array("178","한글","English"),
	array("179","한글","English"),
	array("180","한글","English"),
	array("181","한글","English"),
	array("182","한글","English"),
	array("183","한글","English"),
	array("184","한글","English"),
	array("185","한글","English"),
	array("186","한글","English"),
	array("187","한글","English"),
	array("188","한글","English"),
	array("189","한글","English"),
	array("190","한글","English"),
	array("191","한글","English"),
	array("192","한글","English"),
	array("193","한글","English"),
	array("194","한글","English"),
	array("195","한글","English"),
	array("196","한글","English"),
	array("197","한글","English"),
	array("198","한글","English"),
	array("199","한글","English"),
	array("200","한글","English")
);

$_menuArray = array(
	array("0","환경설정","Configuration"),
	array("1","기본환경설정","Configuration"),
	array("2","관리권한설정","Not a refund of our store-Error(2)"),
	array("3","세션파일삭제","Return code error-Error(3)"),
	array("4","한글","English"),
	array("5","한글","English"),
	array("6","한글","English"),
	array("7","한글","English"),
	array("8","한글","English"),
	array("9","한글","English"),

	array("10","상품관리","Product List"),
	array("11","상품목록","Product List"),
	array("12","상품등록","Register Product"),
	array("13","가격설정","Price setting"),
	array("14","한글","English"),
	array("15","한글","English"),
	array("16","한글","English"),
	array("17","한글","English"),
	array("18","한글","English"),
	array("19","한글","English"),
	
	array("20","매입목록","Purchase List"),
	array("21","매입거래대장","Purchase account"),
	array("22","발주주문","Purchase order"),
	array("23","장바구니","Cart"),
	array("24","한글","English"),
	array("25","한글","English"),
	array("26","한글","English"),
	array("27","한글","English"),
	array("28","한글","English"),
	array("29","한글","English"),
	array("30","한글","English"),

	array("31","출고목록","Sales list"),
	array("32","출고거래대장","Sales account"),
	array("33","한글","English"),
	array("34","한글","English"),
	array("35","한글","English"),
	array("36","한글","English"),
	array("37","한글","English"),
	array("38","한글","English"),
	array("39","한글","English"),
	array("40","한글","English"),

	array("41","재고목록","Stock info"),
	array("42","입출고현황","Stock List"),
	array("43","손망실목록","Loss List"),
	array("44","한글","English"),
	array("45","한글","English"),
	array("46","한글","English"),
	array("47","한글","English"),
	array("48","한글","English"),
	array("49","한글","English"),
	array("50","한글","English"),

	array("51","매장관리","Store List"),
	array("52","한글","English"),
	array("53","한글","English"),
	array("54","한글","English"),
	array("55","한글","English"),
	array("56","한글","English"),
	array("57","한글","English"),
	array("58","한글","English"),
	array("59","한글","English"),
	array("60","한글","English"),

	array("61","바코드발급관리","Barcode list"),
	array("62","한글","English"),
	array("63","한글","English"),
	array("64","한글","English"),
	array("65","한글","English"),
	array("66","한글","English"),
	array("67","한글","English"),
	array("68","한글","English"),
	array("69","한글","English"),
	array("70","한글","English"),

	array("71","카테고리관리","Category"),
	array("72","제품카테고리","Product cate"),
	array("73","기기카테고리","Device cate"),
	array("74","한글","English"),
	array("75","한글","English"),
	array("76","한글","English"),
	array("77","한글","English"),
	array("78","한글","English"),
	array("79","한글","English"),
	array("80","한글","English"),

	array("81","게시판","Board"),
	array("82","한글","English"),
	array("83","한글","English"),
	array("84","한글","English"),
	array("85","한글","English"),
	array("86","한글","English"),
	array("87","한글","English"),
	array("88","한글","English"),
	array("89","한글","English"),
	array("90","한글","English"),

	array("91","한글","English"),
	array("92","한글","English"),
	array("93","한글","English"),
	array("94","한글","English"),
	array("95","한글","English"),
	array("96","한글","English"),
	array("97","한글","English"),
	array("98","한글","English"),
	array("99","한글","English"),

	array("100","매장출고요청","Order from store"),
	array("101","매장반품요청","Return from store"),
	array("102","로그아웃","Log out"),
	array("103","한글","English"),
	array("104","한글","English"),
	array("105","한글","English"),
	array("106","한글","English"),
	array("107","한글","English"),
	array("108","한글","English"),
	array("109","한글","English"),
	array("110","한글","English"),

	// 매장메뉴
	array("111","판매/반품","Sales/Return"),
	array("112","판매분주문","Order"),
	array("113","판매목록","Sales list"),
	array("114","매입목록","Purchase list"),
	array("115","거래대장","Account"),
	array("116","재고목록","Stock list"),
	array("117","가격설정","Price setting"),
	array("118","쇼핑몰","Mall"),
	array("119","장바구니","Cart"),
	array("120","한글","English"),
	array("121","한글","English"),
	array("122","한글","English"),
	array("123","한글","English"),
	array("124","한글","English"),
	array("125","한글","English"),
	array("126","한글","English"),
	array("127","한글","English"),
	array("128","한글","English"),
	array("129","한글","English"),
	array("130","한글","English"),
	array("131","한글","English"),
	array("132","한글","English"),
	array("133","한글","English"),
	array("134","한글","English"),
	array("135","한글","English"),
	array("136","한글","English"),
	array("137","한글","English"),
	array("138","한글","English"),
	array("139","한글","English"),
	array("140","한글","English")
);

$_txtArray = array(
	// 검색공통
	array("0","상품목록","Product List"),
	array("1","카테고리","Category"),
	array("2","선택하세요","Select"),
	array("3","적용기기","Device"),
	array("4","가격대","Price"),
	array("5","판매옵션","Sales option"),
	array("6","반품허용","Returnable"),
	array("7","오픈마켓판매허용","Open market"),
	array("8","브랜드상품여부","Brand"),
	array("9","소비자가준수","Keep price"),
	array("10","상품아이콘","Icons"),
	array("11","인기상품","Popular"),
	array("12","신상품","New"),
	array("13","추천상품","Recommend"),
	array("14","매장특가","Special offer"),
	array("15","검색어","Keyword"),
	array("16","검색단어입력","Enter keyword"),
	array("17","검색","Search"),
	array("18","검색초기화","Initialize"),
	array("19","색상별 분리","Seperate color"),

	// 타이틀 
	// pd_list.php
	array("20","번호","No."),
	array("21","이미지","Image"),
	array("22","바코드","Barcode"),
	array("23","판매상태","Sales Status"),
	array("24","상품명","Prod Name"),
	array("25","제품가격","Price"),
	array("26","재고현황","Stock Info"),
	array("27","등록일","Registered Date"),
	array("28","바코드발행","Issue barcode"),
	array("29","매입원가","Purchase price"),
	array("30","도매가","Wholesale price"),
	array("31","소비자가","Retail price"),
	array("32","매장판매가","Store price"),
	array("33","누적입고","Stock-in"),
	array("34","누적출고","Stock-out"),
	array("35","양품재고","Qualified"),
	array("36","미노출","Hide"),
	array("37","노출중","Expose"),
	array("38","노출상태","Expose Status"),
	array("39","삭제됨","Deleted"),
	array("40","판매일시중지","On hold"),
	array("41","판매중단","Stopped"),
	array("42","판매중","On sale"),
	array("43","발행","Issue"),
	array("44","자료가 없습니다","No lists"),
	array("45","바코드일괄발행","Issue barcode at once"),
	array("46","상품개별등록","Register product"),
	array("47","파일선택","Select file"),
	array("48","상품 엑셀파일 등록","Register Excel file"),
	array("49","선택적용","Select Apply"),

	// pd_write.php
	array("50","상품복사","Copy"),
	array("51","선택삭제","Select Delete"),
	array("52","삭제","Delete"),
	array("53","기본정보","Basic Info"),
	array("54","제품명에 ^,|,|| 등의 특수문자 입력불가","Special characters such as ^,|,|| are not available in Product name"),
	array("55","브랜드/원산지","Brand/Origin"),
	array("56","매입가격설정","Set purchase price"),
	array("57","제품가격설정","Set product price"),
	array("58","제품간략설명","Description"),
	array("59","상세정보","Detail info"),
	array("60","바코드/색상(디자인)","Barcode/Color(Design)"),
	array("61","발주수량","Order Quantity"),
	array("62","버튼","Button"),
	array("63","장바구니","In cart"),
	array("64","제품 이미지","Product Images"),
	array("65","대표 이미지","Main image"),
	array("66","상세 이미지","Detail image"),
	array("67","등록","Register"),
	array("68","수정","Modify"),
	array("69","색상(디자인)","Color(Design)"),
	array("70","적용","Apply"),
	array("71","인기상품","Popular"),
	array("72","인기상품","Popular"),
	array("73","인기상품","Popular"),
	array("74","인기상품","Popular"),
	array("75","인기상품","Popular"),
	array("76","인기상품","Popular"),
	array("77","인기상품","Popular"),
	array("78","인기상품","Popular"),
	array("79","인기상품","Popular"),
	array("80","인기상품","Popular"),
	array("81","인기상품","Popular"),
	array("82","인기상품","Popular"),
	array("83","인기상품","Popular"),
	array("84","인기상품","Popular"),
	array("85","인기상품","Popular"),
	array("86","인기상품","Popular"),
	array("87","인기상품","Popular"),
	array("88","인기상품","Popular"),
	array("89","인기상품","Popular"),
	array("90","인기상품","Popular"),
	array("91","인기상품","Popular"),
	array("92","인기상품","Popular"),
	array("93","인기상품","Popular"),
	array("94","인기상품","Popular"),
	array("95","인기상품","Popular"),
	array("96","인기상품","Popular"),
	array("97","인기상품","Popular"),
	array("98","인기상품","Popular"),
	array("99","인기상품","Popular"),
	array("100","인기상품","Popular"),

	// set_price.php
	array("101","","Popular"),
	array("102","인기상품","Popular"),
	array("103","인기상품","Popular"),
	array("104","인기상품","Popular"),
	array("105","인기상품","Popular"),
	array("106","인기상품","Popular"),
	array("107","인기상품","Popular"),
	array("108","인기상품","Popular"),
	array("109","인기상품","Popular"),
	array("110","인기상품","Popular"),

	//maeip.php
	array("111","매입목록","Purchase List"),
	array("112","구분","Classification"),
	array("113","매입","Purchase"),
	array("114","반품","Return"),
	array("115","매입기간","Purchase date"),
	array("116","시작일","Start date"),
	array("117","종료일","End date"),
	array("118","오늘","Today"),
	array("119","어제","Yesterday"),
	array("120","금월","This month"),
	array("121","전월","Prev month"),
	array("122","상품명/비고","Prod name/etc"),
	array("123","반품대기","Ready to return"),
	array("124","요청일","Registered date"),
	array("125","요청내용","Record"),
	array("126","거래금액","Transaction amount"),
	array("127","처리상태","Process status"),
	array("128","발주취소","Order cancelled"),
	array("129","매입요청","Order received"),
	array("130","발송준비중","Ready to send"),
	array("131","발송완료","Sent"),
	array("132","인수확인중","Checking products"),
	array("133","인수완료","Receive complete"),
	array("134","반품취소","Cancelled"),
	array("135","반품요청","Return received"),
	array("136","반품준비중","Ready to return"),
	array("137","반품출고완료","Returned to seller"),
	array("138","반품건확인중","Checking products"),
	array("139","처리완료","Return complete"),
	array("140","발주상태","Order status"),
	array("141","반품상태","Return status"),
	array("142","발주건 발송","Send to center"),
	array("143","인기상품","Popular"),
	array("144","인기상품","Popular"),
	array("145","인기상품","Popular"),
	array("146","인기상품","Popular"),
	array("147","인기상품","Popular"),
	array("148","인기상품","Popular"),
	array("149","인기상품","Popular"),
	array("150","인기상품","Popular"),
	
	//account1.php
	array("151","매입거래대장","Purchase account"),
	array("152","담당직원","Employee"),
	array("153","적요","Briefs"),
	array("154","누적거래액","Transaction amount sum"),
	array("155","예치금충전","Deposit"),
	array("156","기타","Etc"),
	array("157","외상","Credit"),
	array("158","현금","Cash"),
	array("159","전액할인","For free"),
	array("160","거래수단","Pay method"),
	array("161","인기상품","Popular"),
	array("162","인기상품","Popular"),
	array("163","인기상품","Popular"),
	array("164","인기상품","Popular"),
	array("165","인기상품","Popular"),
	array("166","인기상품","Popular"),
	array("167","인기상품","Popular"),
	array("168","인기상품","Popular"),
	array("169","인기상품","Popular"),
	array("170","인기상품","Popular"),

	//pd_order.php
	array("171","발주주문","Purchase order"),
	array("172","장바구니담기","Add to cart"),
	array("173","검색기간","Order date"),
	array("174","매입단가","Purchase price"),
	array("175","주문중","In cart"),
	array("176","인기상품","Popular"),
	array("177","인기상품","Popular"),
	array("178","인기상품","Popular"),
	array("179","인기상품","Popular"),
	array("180","인기상품","Popular"),
	array("181","인기상품","Popular"),
	array("182","인기상품","Popular"),
	array("183","인기상품","Popular"),
	array("184","인기상품","Popular"),
	array("185","인기상품","Popular"),
	array("186","인기상품","Popular"),
	array("187","인기상품","Popular"),

	//fod_cart.php
	array("188","장바구니목록","Cart list"),
	array("189","발주처","Order to"),
	array("190","발주 총금액","Order amount total"),
	array("191","발주메모","Memo"),
	array("192","장바구니 비우기","Clear cart"),
	array("193","선택상품발주","Order"),
	array("194","인기상품","Popular"),
	array("195","인기상품","Popular"),
	array("196","인기상품","Popular"),
	array("197","인기상품","Popular"),
	array("198","인기상품","Popular"),
	array("199","인기상품","Popular"),
	array("200","인기상품","Popular"),
	array("201","인기상품","Popular"),
	array("202","인기상품","Popular"),
	array("203","인기상품","Popular"),
	array("204","인기상품","Popular"),

	// choolgo.php
	array("205","출고목록","Sales list"),
	array("206","출고","Order"),
	array("207","반품","Return"),
	array("208","출고기간","Date"),
	array("209","상품명/매장명","Prod name/Store name"),
	array("210","매장코드","Store code"),
	array("211","미인수건 있음","Missing"),
	array("212","인기상품","Popular"),
	array("213","인기상품","Popular"),
	array("214","인기상품","Popular"),
	array("215","인기상품","Popular"),
	array("216","인기상품","Popular"),
	array("217","인기상품","Popular"),
	array("218","인기상품","Popular"),
	array("219","인기상품","Popular"),
	array("220","인기상품","Popular"),
	array("221","인기상품","Popular"),
	array("222","인기상품","Popular"),

	// account2.php
	array("223","출고거래대장","Sales account"),
	array("224","수금","Deposit"),
	array("225","판매","Sales"),
	array("226","매장명/아이디","StoreName/ID"),
	array("227","금액","Price"),
	array("228","결제금액","Pay amount"),
	array("229","매장","Store"),
	array("230","본사","Center"),
	array("231","누적구매","Purchase sum"),
	array("232","잔여결제액","Deposit"),
	array("233","누적판매","Sales sum"),
	array("234","누적판매손익","Sales Balance"),
	array("235","거래기간","Date"),
	array("236","반품","Return"),
	array("237","기타","Etc"),
	array("238","인기상품","Popular"),
	array("239","인기상품","Popular"),
	array("240","인기상품","Popular"),
	array("241","인기상품","Popular"),
	array("242","인기상품","Popular"),
	array("243","인기상품","Popular"),
	array("244","인기상품","Popular"),
	array("245","인기상품","Popular"),
	array("246","인기상품","Popular"),
	array("247","인기상품","Popular"),
	array("248","인기상품","Popular"),

	// stock_io.php
	array("249","재고목록","Stock List"),
	array("250","입고일","Stock in date"),
	array("251","개별제품 분리","Seperate"),
	array("252","입출고 현황","In-Out history"),
	array("253","양품","Qualified"),
	array("254","불량","Defected"),
	array("255","다시시작","Popular"),
	array("256","발주건 외 개별입고처리","Stock in manually"),
	array("257","확인","Confirm"),
	array("258","재고수량","Stock info"),
	array("259","입고수량","Stock in"),
	array("260","매입처반품출고","Returned to seller"),
	array("261","손망실처리","Loss"),
	array("262","입고","Stock in"),
	array("263","매장반품입고","Returned from store"),
	array("264","매입처반품거절","Return rejected"),
	array("265","매입처반품준비","Ready to return"),
	array("266","발주건입고","Order"),
	array("267","개별입고","Manual"),
	array("268","출고","Stock out"),
	array("269","매장반품","Returned from store"),
	array("270","양품전환","Change to qualified"),
	array("271","손망실전환","Change to loss"),
	array("272","매입처반품대기","Ready to return"),
	array("273","불량전환","Change to defected"),
	array("274","재고상태","Stock status"),
	array("275","제품상태","Stock quality"),
	array("276","판매","Sold to store"),
	array("277","입고가격","Purchase price"),
	array("278","출고준비중","Ready to stock-out"),
	array("279","인기상품","Popular"),
	array("280","인기상품","Popular"),
	array("281","인기상품","Popular"),
	array("282","인기상품","Popular"),
	array("283","인기상품","Popular"),
	array("284","인기상품","Popular"),
	array("285","인기상품","Popular"),
	array("286","인기상품","Popular"),
	array("287","인기상품","Popular"),
	array("288","인기상품","Popular"),
	array("289","인기상품","Popular"),
	array("290","인기상품","Popular"),

	// loss_io.php
	array("291","손망실목록","Loss List"),
	array("292","손망실처리일","Registered date"),
	array("293","처리사유","Loss reason"),
	array("294","재고조사손실분","Stock inspection"),
	array("295","불량재고손실분","Defected product"),
	array("296","기타손실분","Etc"),
	array("297","매입처반품거절손실분","Rejected by seller"),
	array("298","매장 미인수건 손실분","Not received by store"),
	array("299","인기상품","Popular"),
	array("300","인기상품","Popular"),
	array("301","한글","English"),
	array("302","한글","English"),
	array("303","한글","English"),
	array("304","한글","English"),
	array("305","한글","English"),
	array("306","한글","English"),
	array("307","한글","English"),
	array("308","한글","English"),
	array("309","한글","English"),
	array("310","한글","English"),

	// ag_list.php, ag_info.php, ag_form.php
	array("311","매장목록","Store List"),
	array("312","매장명","Store name"),
	array("313","대표 ID","Main ID"),
	array("314","연락처","Tel"),
	array("315","대표자명","Name of representative"),
	array("316","매장주소","Store address"),
	array("317","예치금충전","Charge deposit"),
	array("318","충전","Charge"),
	array("319","매장추가","Add store"),
	array("320","비밀번호","Password"),
	array("321","연락처/핸드폰","Tel/Hp"),
	array("322","팩스/이메일","Fax/E-mail"),
	array("323","가입일","Registered date"),
	array("324","회원메모","Memo"),
	array("325","매장직원정보","Store employees"),
	array("326","직원추가","Add employee"),
	array("327","직원명","Name"),
	array("328","직원ID","ID"),
	array("329","연락처","Tel"),
	array("330","이메일","E-mail"),
	array("331","메뉴 접근권한 설정","Set authority to access menu"),
	array("332","매장정보","Store Info"),
	array("333","비밀번호 변경시에만 입력하십시오","Enter new password only when you change the present password."),
	array("334","비밀번호 확인","Password again"),
	array("335","매장등록","Add store"),
	array("336","등록완료","Register"),
	array("337","적립금 설정","Membership setting"),
	array("338","현금적립율","Save rate for cash"),
	array("339","적립금 사용가능액","M.ship use limit"),
	array("340","적립금부여가능 직원레벨","Employee level to control M.ship"),
	array("341","구매금액에 대한 적립율","Save this percent of purchasing price into member's account."),
	array("342","설정한 금액이상이 되어야 적립금 사용가능","Members can use M.ship from this amount of M.ship"),
	array("343","적립금 부여/삭감 가능한 직원레벨","Employees can plus or minus member's M.ship from this level"),
	array("344","카드적립율","Save rate for card"),
	array("345","한글","English"),
	array("346","한글","English"),
	array("347","한글","English"),
	array("348","한글","English"),
	array("349","한글","English"),
	array("350","한글","English"),

	// bcode_issue_list.php
	array("351","바코드발급목록","Barcode Issued list"),
	array("352","발급(주문)번호","Issue(order) code"),
	array("353","발급총수량","Issued count"),
	array("354","발급일","Issue date"),
	array("355","엑셀출력","Excel data"),
	array("356","발주건일괄발급","From order"),
	array("357","개별바코드발급","Manually"),
	array("358","엑셀저장","Save to excel"),
	array("359","한글","English"),
	array("360","한글","English"),
	array("361","한글","English"),
	array("362","한글","English"),
	array("363","한글","English"),
	array("364","한글","English"),
	array("365","한글","English"),
	array("366","한글","English"),
	array("367","한글","English"),
	array("368","한글","English"),
	array("369","한글","English"),
	array("370","한글","English"),
	array("371","한글","English"),

	// 카테고리관련
	array("372","카테고리관리","Category"),
	array("373","카테고리제목","Name"),
	array("374","상품수","Prod count"),
	array("375","수정","Modify"),
	array("376","서브카테고리","Sub category"),
	array("377","노출순서저장","Save expose order"),
	array("378","카테고리추가","Add category"),
	array("379","상위카테고리","Parent category"),
	array("380","생성","Add category"),
	array("381","영문카테고리명","Name in english"),
	array("382","한글","English"),
	array("383","한글","English"),
	array("384","한글","English"),
	array("385","한글","English"),
	array("386","한글","English"),
	array("387","한글","English"),
	array("388","한글","English"),
	array("389","한글","English"),
	array("390","한글","English"),

	// ajax_get_aoddetail_skin.php
	array("391","발주상세","Order info"),
	array("392","발주내용","Order"),
	array("393","발송내용","Send"),
	array("394","인수내용","Receive"),
	array("395","주문건 출고처리","Stock out"),
	array("396","출고수량","Send"),
	array("397","인수수량","Receive"),
	array("398","출고메모","Memo"),
	array("399","출고완료","Send"),
	array("400","미인수건 정산","Balance transaction"),
	array("401","합계","Summary"),
	array("402","발주수량","Order"),
	array("403","한글","English"),
	array("404","한글","English"),
	array("405","한글","English"),
	array("406","한글","English"),
	array("407","한글","English"),
	array("408","한글","English"),
	array("409","한글","English"),
	array("410","한글","English"),

	// ajax_get_abpdetail_skin.php
	array("411","반품상세","Return info"),
	array("412","반품내용","Record"),
	array("413","반품취소","Return cancelled"),
	array("414","처리내용","Result"),
	array("415","출고일","Stock out date"),
	array("416","출고가격","Sales price"),
	array("417","제품상태","Prod quality"),
	array("418","반품처리","Result"),
	array("419","거부","Reject"),
	array("420","양품입고","Qualified"),
	array("421","불량입고","Defected"),
	array("422","반품사유","Store memo"),
	array("423","처리메모","Center memo"),
	array("424","승인","Accept"),
	array("425","메모","Memo"),
	array("426","처리완료","Confirm"),
	array("427","한글","English"),
	array("428","한글","English"),
	array("429","한글","English"),
	array("430","한글","English"),
	array("431","한글","English"),
	array("432","한글","English"),
	array("433","한글","English"),
	array("434","한글","English"),
	array("435","한글","English"),
	array("436","한글","English"),

	// ajax_get_fbpdetail_skin.php
	array("437","반품사유","Center memo"),
	array("438","처리메모","Seller memo"),
	array("439","한글","English"),
	array("440","한글","English"),
	array("441","한글","English"),
	array("442","한글","English"),
	array("443","한글","English"),
	array("444","한글","English"),
	array("445","한글","English"),
	array("446","한글","English"),
	array("447","한글","English"),
	array("448","한글","English"),
	array("449","한글","English"),
	array("450","한글","English"),

	// ajax_get_oddetail_skin.php
	array("451","발주취소","Cancel order"),
	array("452","인수메모","Memo"),
	array("453","인수확인","Confirm receive"),
	array("454","발주단가","Purchase price"),
	array("455","발송메모","Memo"),
	array("456","한글","English"),
	array("457","한글","English"),
	array("458","한글","English"),
	array("459","한글","English"),
	array("460","한글","English"),
	array("461","한글","English"),
	array("462","한글","English"),
	array("463","한글","English"),
	array("464","한글","English"),
	array("465","한글","English"),
	array("466","한글","English"),

	// 바코드 발급관련
	array("467","한글","English"),
	array("468","한글","English"),
	array("469","한글","English"),
	array("470","한글","English"),
	array("471","한글","English"),
	array("472","한글","English"),
	array("473","한글","English"),
	array("474","한글","English"),
	array("475","한글","English"),
	array("476","한글","English"),
	array("477","한글","English"),
	array("478","한글","English"),
	array("479","한글","English"),
	array("480","한글","English"),
	array("481","한글","English"),
	array("482","한글","English"),
	array("483","한글","English"),
	array("484","한글","English"),
	array("485","한글","English"),
	array("486","한글","English"),
	array("487","한글","English"),
	array("488","한글","English"),
	array("489","한글","English"),
	array("490","한글","English"),

	// layer 관련
	array("491","매장부담액","Store charge"),
	array("492","정산수단","Charge method"),
	array("493","정산일","Charge date"),
	array("494","결제금액","Pay amount"),
	array("495","결제수단","Pay method"),
	array("496","결제일","Pay date"),
	array("497","직원 아이디","ID"),
	array("498","반품대기목록","Return ready lists"),
	array("499","반품출고","Send returns"),
	array("500","임시저장","Save temporar"),
	array("501","복사원본","Source product"),
	array("502","복사대상 기본정보","Basic info"),
	array("503","복사대상 상세정보","Detail info"),
	array("504","복사대상 이미지","Images"),
	array("505","재고조사 손망실 처리","Loss-Stock inspection"),
	array("506","불량재고 손망실 처리","Loss-Defected product"),
	array("507","손망실 처리","Loss"),
	array("508","반품메모","Memo"),
	array("509","매입처반품","Return to seller"),
	array("510","한글","English"),
	array("511","한글","English"),
	array("512","한글","English"),
	array("513","한글","English"),
	array("514","한글","English"),
	array("515","한글","English"),
	array("516","한글","English"),
	array("517","한글","English"),
	array("518","한글","English"),
	array("519","한글","English"),
	array("520","한글","English"),
	array("521","한글","English"),
	array("522","한글","English"),
	array("523","한글","English"),
	array("524","한글","English"),
	array("525","한글","English"),
	array("526","한글","English"),
	array("527","한글","English"),
	array("528","한글","English"),
	array("529","한글","English"),
	array("530","한글","English"),

	// 매장관리자
	array("531","매장양품재고","Qualified"),
	array("532","기간판매","Sold"),
	array("533","누적판매","Sold sum"),
	array("534","판매등록","Sales"),
	array("535","금액합계","Price total"),
	array("536","할인합계","Discount total"),
	array("537","총지불금액","Pay total"),
	array("538","메모","Memo"),
	array("539","카드","Card"),
	array("540","현금","Cash"),
	array("541","카드+현금","Card+Cash"),
	array("542","판매등록","Register"),
	array("543","할인금액","Discount"),
	array("544","소계","Sub total"),
	array("545","상품바코드를 입력하십시오","Enter product barcode"),
	array("546","반품등록","Return"),
	array("547","총반품금액","Return total"),
	array("548","결제취소수단","Pay cancel method"),
	array("549","반품등록","Register"),
	array("550","제품판매가","Sales price"),
	array("551","지불금액","Pay total"),
	array("552","반품금액","Return total"),
	array("553","반품상태","Return status"),
	array("554","금일 판매(반품) 현황","Sales/Return of today"),
	array("555","판매(반품)일시","Sales(Return) Date"),
	array("556","판매(반품)내역","Sales(Return) Record"),
	array("557","결제(취소)금액","Pay(Cancel) amount"),
	array("558","등록직원","Employee in charge"),
	array("559","판매","Sales"),
	array("560","반품","Return"),
	array("561","판매상태","Status"),
	array("562","판매기간","Sales date"),
	array("563","손망실","Loss"),
	array("564","다시시작","Restart"),
	array("565","현재 매장보유 양품재고","Qualified count"),
	array("566","읽은 바코드 수","Read count"),
	array("567","재고조사 모드","Stock inspection"),
	array("568","판매","Sold to customer"),
	array("569","본사반품출고","Returned to center"),
	array("570","고객반품","Returned from customer"),
	array("571","본사반품거절","Rejected by center"),
	array("572","본사반품준비","Ready to return"),
	array("573","본사반품대기","Ready to return"),
	array("574","선택재고 손망실처리","Select Loss comfirm"),
	array("575","상품상세","Product info"),
	array("576","반품상품 선택","Select product to return"),
	array("577","판매코드","Sales code"),
	array("578","판매내용","Sales record"),
	array("579","판매일","Sold date"),
	array("580","판매메모","Memo"),
	array("581","선택","Select"),
	array("582","본사반품","Return to center"),
	array("583","예치금","Deposit"),
	array("584","회원등록","Register"),
	array("585","정보수정","Modify"),
	array("586","멤버쉽","Membership"),
	array("587","회원정보","Member Info"),
	array("588","총 보유 M.ship","M.ship Total"),
	array("589","사용금액입력","M.ship amount"),
	array("590","적립/사용 내역","M.ship history"),
	array("591","적립내용","Description"),
	array("592","적립일시","Date"),
	array("593","누적적립금","M.ship Sum"),
	array("594","적립된 내역이 없습니다.","No data"),
	array("595","확인","Apply M.ship"),
	array("596","취소","Not apply M.ship"),
	array("597","검색기간","Period"),
	array("598","판매/반품 합계","Sales/Return"),
	array("599","할인/적립금 사용","DC/M.ship Total"),
	array("600","매출총액","Sales Total"),
	array("601","매출원가","Cost"),
	array("602","매출손익","Revenue"),
	array("603","(매출총액 = 판매합계 - 반품합계)","(Sales Total = Sales - Return)"),
	array("604","(매출손익 = 매출총액 - 매출원가)","(Revenue = Sales Total - Cost)"),
	array("605","적립금","M.ship"),
	array("606","할인","DC"),
	array("607","건","times"),
	array("608","개","ea"),
	array("609","한글","English"),
	array("610","한글","English"),
	array("611","한글","English"),
	array("612","한글","English"),
	array("613","한글","English"),
	array("614","한글","English"),
	array("615","한글","English"),
	array("616","한글","English"),
	array("617","한글","English"),
	array("618","한글","English"),
	array("619","한글","English"),
	array("620","한글","English"),
	array("621","한글","English"),
	array("622","한글","English"),
	array("623","한글","English"),
	array("624","한글","English"),
	array("625","한글","English"),
	array("626","한글","English"),
	array("627","한글","English"),
	array("628","한글","English"),
	array("629","한글","English"),
	array("630","한글","English"),
	array("631","한글","English"),
	array("632","한글","English"),
	array("633","한글","English"),
	array("634","한글","English"),
	array("635","한글","English"),
	array("636","한글","English"),
	array("637","한글","English"),
	array("638","한글","English"),
	array("639","한글","English"),
	array("640","한글","English"),
	array("641","한글","English"),
	array("642","한글","English"),
	array("643","한글","English"),
	array("644","한글","English"),
	array("645","한글","English"),
	array("646","한글","English"),
	array("647","한글","English"),
	array("648","한글","English"),
	array("649","한글","English"),
	array("650","한글","English"),
	array("651","한글","English"),
	array("652","한글","English"),
	array("653","한글","English"),
	array("654","한글","English"),
	array("655","한글","English"),
	array("656","한글","English"),
	array("657","한글","English"),
	array("658","한글","English"),
	array("659","한글","English"),
	array("660","한글","English"),
	array("661","한글","English"),
	array("662","한글","English"),
	array("663","한글","English"),
	array("664","한글","English"),
	array("665","한글","English"),
	array("666","한글","English"),
	array("667","한글","English"),
	array("668","한글","English"),
	array("669","한글","English"),
	array("670","한글","English"),
	array("671","한글","English"),
	array("672","한글","English"),
	array("673","한글","English"),
	array("674","한글","English"),
	array("675","한글","English"),
	array("676","한글","English"),
	array("677","한글","English"),
	array("678","한글","English"),
	array("679","한글","English"),
	array("680","한글","English"),
	array("681","한글","English"),
	array("682","한글","English"),
	array("683","한글","English"),
	array("684","한글","English"),
	array("685","한글","English"),
	array("686","한글","English"),
	array("687","한글","English"),
	array("688","한글","English"),
	array("689","한글","English"),
	array("690","한글","English"),
	array("691","한글","English"),
	array("692","한글","English"),
	array("693","한글","English"),
	array("694","한글","English"),
	array("695","한글","English"),
	array("696","한글","English"),
	array("697","한글","English"),
	array("698","한글","English"),
	array("699","한글","English"),
	array("700","한글","English"),
	array("701","한글","English"),
	array("702","한글","English"),
	array("703","한글","English"),
	array("704","한글","English"),
	array("705","한글","English"),
	array("706","한글","English"),
	array("707","한글","English"),
	array("708","한글","English"),
	array("709","한글","English"),
	array("710","한글","English"),
	array("711","한글","English"),
	array("712","한글","English"),
	array("713","한글","English"),
	array("714","한글","English"),
	array("715","한글","English"),
	array("716","한글","English"),
	array("717","한글","English"),
	array("718","한글","English"),
	array("719","한글","English"),
	array("720","한글","English"),
	array("721","한글","English"),
	array("722","한글","English"),
	array("723","한글","English"),
	array("724","한글","English"),
	array("725","한글","English"),
	array("726","한글","English"),
	array("727","한글","English"),
	array("728","한글","English"),
	array("729","한글","English"),
	array("730","한글","English"),
	array("731","한글","English"),
	array("732","한글","English"),
	array("733","한글","English"),
	array("734","한글","English"),
	array("735","한글","English"),
	array("736","한글","English"),
	array("737","한글","English"),
	array("738","한글","English"),
	array("739","한글","English"),
	array("740","한글","English"),
	array("741","한글","English"),
	array("742","한글","English"),
	array("743","한글","English"),
	array("744","한글","English"),
	array("745","한글","English"),
	array("746","한글","English"),
	array("747","한글","English"),
	array("748","한글","English"),
	array("749","한글","English"),
	array("750","한글","English"),
	array("751","한글","English"),
	array("752","한글","English"),
	array("753","한글","English"),
	array("754","한글","English"),
	array("755","한글","English"),
	array("756","한글","English"),
	array("757","한글","English"),
	array("758","한글","English"),
	array("759","한글","English"),
	array("760","한글","English"),
	array("761","한글","English"),
	array("762","한글","English"),
	array("763","한글","English"),
	array("764","한글","English"),
	array("765","한글","English"),
	array("766","한글","English"),
	array("767","한글","English"),
	array("768","한글","English"),
	array("769","한글","English"),
	array("770","한글","English"),
	array("771","한글","English"),
	array("772","한글","English"),
	array("773","한글","English"),
	array("774","한글","English"),
	array("775","한글","English"),
	array("776","한글","English"),
	array("777","한글","English"),
	array("778","한글","English"),
	array("779","한글","English"),
	array("780","한글","English"),
	array("781","한글","English"),
	array("782","한글","English"),
	array("783","한글","English"),
	array("784","한글","English"),
	array("785","한글","English"),
	array("786","한글","English"),
	array("787","한글","English"),
	array("788","한글","English"),
	array("789","한글","English"),
	array("790","한글","English"),
	array("791","한글","English"),
	array("792","한글","English"),
	array("793","한글","English"),
	array("794","한글","English"),
	array("795","한글","English"),
	array("796","한글","English"),
	array("797","한글","English"),
	array("798","한글","English"),
	array("799","한글","English"),
	array("800","한글","English"),
	array("801","한글","English"),
	array("802","한글","English"),
	array("803","한글","English"),
	array("804","한글","English"),
	array("805","한글","English"),
	array("806","한글","English"),
	array("807","한글","English"),
	array("808","한글","English"),
	array("809","한글","English"),
	array("810","한글","English"),
	array("811","한글","English"),
	array("812","한글","English"),
	array("813","한글","English"),
	array("814","한글","English"),
	array("815","한글","English"),
	array("816","한글","English"),
	array("817","한글","English"),
	array("818","한글","English"),
	array("819","한글","English"),
	array("820","한글","English"),
	array("821","한글","English"),
	array("822","한글","English"),
	array("823","한글","English"),
	array("824","한글","English"),
	array("825","한글","English"),
	array("826","한글","English"),
	array("827","한글","English"),
	array("828","한글","English"),
	array("829","한글","English"),
	array("830","한글","English"),
	array("831","한글","English"),
	array("832","한글","English"),
	array("833","한글","English"),
	array("834","한글","English"),
	array("835","한글","English"),
	array("836","한글","English"),
	array("837","한글","English"),
	array("838","한글","English"),
	array("839","한글","English"),
	array("840","한글","English"),
	array("841","한글","English"),
	array("842","한글","English"),
	array("843","한글","English"),
	array("844","한글","English"),
	array("845","한글","English"),
	array("846","한글","English"),
	array("847","한글","English"),
	array("848","한글","English"),
	array("849","한글","English"),
	array("850","한글","English"),
	array("851","한글","English"),
	array("852","한글","English"),
	array("853","한글","English"),
	array("854","한글","English"),
	array("855","한글","English"),
	array("856","한글","English"),
	array("857","한글","English"),
	array("858","한글","English"),
	array("859","한글","English"),
	array("860","한글","English"),
	array("861","한글","English"),
	array("862","한글","English"),
	array("863","한글","English"),
	array("864","한글","English"),
	array("865","한글","English"),
	array("866","한글","English"),
	array("867","한글","English"),
	array("868","한글","English"),
	array("869","한글","English"),
	array("870","한글","English"),
	array("871","한글","English"),
	array("872","한글","English"),
	array("873","한글","English"),
	array("874","한글","English"),
	array("875","한글","English"),
	array("876","한글","English"),
	array("877","한글","English"),
	array("878","한글","English"),
	array("879","한글","English"),
	array("880","한글","English"),
	array("881","한글","English"),
	array("882","한글","English"),
	array("883","한글","English"),
	array("884","한글","English"),
	array("885","한글","English"),
	array("886","한글","English"),
	array("887","한글","English"),
	array("888","한글","English"),
	array("889","한글","English"),
	array("890","한글","English"),
	array("891","한글","English"),
	array("892","한글","English"),
	array("893","한글","English"),
	array("894","한글","English"),
	array("895","한글","English"),
	array("896","한글","English"),
	array("897","한글","English"),
	array("898","한글","English"),
	array("899","한글","English"),
	array("900","한글","English"),
	array("901","한글","English"),
	array("902","한글","English"),
	array("903","한글","English"),
	array("904","한글","English"),
	array("905","한글","English"),
	array("906","한글","English"),
	array("907","한글","English"),
	array("908","한글","English"),
	array("909","한글","English"),
	array("910","한글","English"),
	array("911","한글","English"),
	array("912","한글","English"),
	array("913","한글","English"),
	array("914","한글","English"),
	array("915","한글","English"),
	array("916","한글","English"),
	array("917","한글","English"),
	array("918","한글","English"),
	array("919","한글","English"),
	array("920","한글","English"),
	array("921","한글","English"),
	array("922","한글","English"),
	array("923","한글","English"),
	array("924","한글","English"),
	array("925","한글","English"),
	array("926","한글","English"),
	array("927","한글","English"),
	array("928","한글","English"),
	array("929","한글","English"),
	array("930","한글","English"),
	array("931","한글","English"),
	array("932","한글","English"),
	array("933","한글","English"),
	array("934","한글","English"),
	array("935","한글","English"),
	array("936","한글","English"),
	array("937","한글","English"),
	array("938","한글","English"),
	array("939","한글","English"),
	array("940","한글","English"),
	array("941","한글","English"),
	array("942","한글","English"),
	array("943","한글","English"),
	array("944","한글","English"),
	array("945","한글","English"),
	array("946","한글","English"),
	array("947","한글","English"),
	array("948","한글","English"),
	array("949","한글","English"),
	array("950","한글","English"),
	array("951","한글","English"),
	array("952","한글","English"),
	array("953","한글","English"),
	array("954","한글","English"),
	array("955","한글","English"),
	array("956","한글","English"),
	array("957","한글","English"),
	array("958","한글","English"),
	array("959","한글","English"),
	array("960","한글","English"),
	array("961","한글","English"),
	array("962","한글","English"),
	array("963","한글","English"),
	array("964","한글","English"),
	array("965","한글","English"),
	array("966","한글","English"),
	array("967","한글","English"),
	array("968","한글","English"),
	array("969","한글","English"),
	array("970","한글","English"),
	array("971","한글","English"),
	array("972","한글","English"),
	array("973","한글","English"),
	array("974","한글","English"),
	array("975","한글","English"),
	array("976","한글","English"),
	array("977","한글","English"),
	array("978","한글","English"),
	array("979","한글","English"),
	array("980","한글","English"),
	array("981","한글","English"),
	array("982","한글","English"),
	array("983","한글","English"),
	array("984","한글","English"),
	array("985","한글","English"),
	array("986","한글","English"),
	array("987","한글","English"),
	array("988","한글","English"),
	array("989","한글","English"),
	array("990","한글","English"),
	array("991","한글","English"),
	array("992","한글","English"),
	array("993","한글","English"),
	array("994","한글","English"),
	array("995","한글","English"),
	array("996","한글","English"),
	array("997","한글","English"),
	array("998","한글","English"),
	array("999","한글","English"),
	array("1000","한글","English")

);

?>
